spring:
  application:
    name:k8s-web
  cloud:
    kubernetes:
      discovery:
        enabled: true
  datasource:
    url: jdbc:mysql://10.168.59.90:3306/k8s?allowPublicKeyRetrieval=true&useSSL=false&user=root&password=040424&useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8088
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

